---

- name: "NFTables-Addons | Timer Cron | {{ addon_key }} | Adding entry"
  ansible.builtin.cron:
    name: "{{ NFT_ADD_HC.cron_prefix }}_{{ addon_key }}"
    minute: "{{ NTF_ADD_CONFIG.timer.cron[addon_key]['minute'] | default(omit, true) }}"
    hour: "{{ NTF_ADD_CONFIG.timer.cron[addon_key]['hour'] | default(omit, true) }}"
    day: "{{ NTF_ADD_CONFIG.timer.cron[addon_key]['day'] | default(omit, true) }}"
    weekday: "{{ NTF_ADD_CONFIG.timer.cron[addon_key]['weekday'] | default(omit, true) }}"
    job: "python3 {{ NTF_ADD_CONFIG.path.lib }}/{{ addon_key }}.py"
