---

- name: NFTables-Addons | Timer | Cron
  ansible.builtin.include_tasks: timer/cron.yml
  when:
    - NFT_ADD_CONFIG.enable.timer | bool
    - NFT_ADD_CONFIG.enable.cron | bool
    - not NFT_ADD_CONFIG.enable.systemd | bool

- name: NFTables-Addons | Timer | Systemd
  ansible.builtin.include_tasks: timer/systemd.yml
  vars:
    systemd_name: "{{ NFT_ADD_CONFIG.timer.systemd.service_prefix }}{{ addon_key }}"
  when:
    - NFT_ADD_CONFIG.enable.timer | bool
    - NFT_ADD_CONFIG.enable.systemd | bool
    - not NFT_ADD_CONFIG.enable.cron | bool
