---

# ansible-playbook -K -D -i inventory/hosts.yml playbook.yml

- name: NFTables Addons
  hosts: all   # should be limited
  become: true
  gather_facts: yes
  roles:
    - ansibleguy.addons_nftables
