---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - name: 'oxlorg.nftables'
    src: 'git+https://github.com/O-X-L/ansible-role-nftables'
