---

- name: NFTables-Addons | IP-List | Copying script
  ansible.builtin.template:
    src: 'templates/usr/lib/nftables/iplist.py.j2'
    dest: "{{ NFT_ADD_CONFIG.path.lib }}/iplist.py"
    owner: 'root'
    group: "{{ NFT_ADD_CONFIG.group }}"
    mode: 0750

- name: NFTables-Addons | IP-List | Adding config
  ansible.builtin.copy:
    content: "{{ data | to_json }}"
    dest: "{{ NFT_ADD_CONFIG.path.addon.dir }}/{{ NFT_ADD_CONFIG.path.addon.iplist_dump }}"
    owner: 'root'
    group: "{{ NFT_ADD_CONFIG.group }}"
    mode: 0640
  vars:
    data: "{{ {NFT_ADD_HC.dump_keys.iplist: NFT_ADD_CONFIG.config.iplists} }}"
  register: nft_iplist_config
  tags: config

- name: NFTables-Addons | IP-List | Updating config
  ansible.builtin.command: "python3 {{ NFT_ADD_CONFIG.path.lib }}/iplist.py"
  changed_when: false
  timeout: 5
  when: nft_iplist_config.changed
  tags: config

- name: NFTables-Addons | IP-List | Timer
  ansible.builtin.include_tasks: timer/main.yml
  vars:
    addon_key: 'iplist'
  args:
    apply:
      tags: iplist
