---

no_prompts: false
debug: false

NFT_CONFIG: {}  # fallback if undefined

# default config => is overwritten by provided config
defaults_nftables_addons:
  enable:
    dns: false
    dns_v6: false
    iplist: false
    iplist_v6: false
    timer: true
    systemd: true
    cron: false
    include: true

  appendix:  # will be appended to the var-names
    ipv4: ''
    ipv6: 'v6'  # IMPORTANT: NEEDS TO DIFFER FROM v4 VARS! As NFTables can only use one IP-protocol at a time

  config:
    iplists: {}
    #  variable:
    #    urls: ['https://check.torproject.org/torbulkexitlist']
    #    separator: "\n"
    #    comment: '#'
    dns_records: {}
    #  variable: ['dns1', 'dns2']

  ext: "{{ NFT_CONFIG.ext | default('nft') }}"  # extensions used for nftables config-files
  path:
    lib: '/usr/lib/nftables'
    base:
      config: "{{ NFT_CONFIG.path.config_file | default('/etc/nftables.conf') }}"
      dir: "{{ NFT_CONFIG.path.config_dir | default('/etc/nftables.d') }}"  # set to empty string if not used
    addon:
      dir: "{{ NFT_CONFIG.path.config_dir | default('/etc/nftables.d') + '/addons' }}"
      dns: 'dns'  # .nft will be appended
      dns_dump: 'dns.json'
      iplist: 'iplist'  # .nft will be appended
      iplist_dump: 'iplist.json'

  cmd_reload: 'sudo systemctl reload nftables.service'  # has to be changed if no systemd is available

  user: 'root'
  group: 'root'

  timer:
    systemd:
      # for date-time format see:
      #   https://wiki.archlinux.org/title/Systemd/Timers
      #   https://silentlad.com/systemd-timers-oncalendar-(cron)-format-explained
      dns: '*:0/15'  # every 15min
      iplist: '*-*-* 00,12:00:00'  # twice a day
      syslog_id_prefix: 'nftables_addon'
      service_prefix: 'ansibleguy.addons_nftables-'

    cron:  # see module: ansible.builtin.cron and https://crontab.guru/
      dns:  # every 15min
        minute: '*/15'
        hour:
        day:
        weekday:
      iplist:  # twice a day
        minute: '0'
        hour: '0,12'
        day:
        weekday:
