---

- name: Prepare Cron-Based Timer
  hosts: test-ag-nftablesaddons-cron
  gather_facts: false
  tasks:
    - name: Installing Role dependencies
      ansible.builtin.apt:
        name: ['cron']
        state: present

- name: Prepare Systemd-Based Timer
  hosts: test-ag-nftablesaddons-systemd
  gather_facts: false
  tasks:
    - name: Installing Role dependencies
      ansible.builtin.apt:
        name: ['systemd']
        state: present

- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Installing troubleshooting utils
      ansible.builtin.apt:
        name: ['less', 'nano', 'net-tools', 'dnsutils', 'iproute2']
        state: present

    - name: Installing Role dependencies
      ansible.builtin.apt:
        name: ['kmod', 'nftables']
        state: present

    - name: Starting & Enabling NFTables
      ansible.builtin.systemd:
        name: 'nftables.service'
        state: started
        enabled: true

    - name: NFTables | Adding config directory
      ansible.builtin.file:
        state: directory
        path: '/etc/nftables.d'
        mode: 0750
        owner: 'root'
        group: 'root'
