---

- name: Prepare
  hosts: all
  vars:
    nftables:
      enable:
        sets: false  # debian (11) kernel 5.x does not support it

      tables:
        example:
          chains:
            incoming:
              vars:
                chain_var: '1.1.1.1'

              hook: 'input'
              rules:
                - sequence: 1
                  raw: 'ct state invalid counter log prefix "DROP invalid sates" drop'
                - seq: 2
                  raw: 'ct state {established, related} counter accept comment "Allow open sessions"'
                - s: 3
                  raw: 'iifname "lo" accept comment "Allow loopback traffic"'

            outgoing:
              hook: 'output'
              policy: 'accept'

  roles:
    - ansibleguy.infra_nftables
