---

- name: Prepare
  hosts: test-ag-nftablesaddons-cron
  tasks:
    - name: Installing Role dependencies
      ansible.builtin.apt:
        name: ['cron']
        state: present

- name: Prepare
  hosts: all
  vars:
    nftables:
      enable:
        sets: false  # debian (11) kernel 5.x does not support it

      tables:
        example:
          chains:
            incoming:
              vars:
                chain_var: '1.1.1.1'

              hook: 'input'
              rules:
                - 'ct state invalid counter log prefix "DROP invalid sates" drop'
                - 'ct state {established, related} counter accept comment "Allow open sessions"'
                - 'iifname "lo" accept comment "Allow loopback traffic"'

            outgoing:
              hook: 'output'
              policy: 'accept'

            route:
              hook: 'forward'
              policy: 'accept'

            prr:
              hook: 'prerouting'
              policy: 'accept'

            por:
              hook: 'postrouting'
              type: 'nat'
              policy: 'accept'

  pre_tasks:
    - name: Installing troubleshooting utils
      ansible.builtin.apt:
        name: ['less', 'nano', 'net-tools', 'dnsutils', 'iproute2']
        state: present

    - name: Installing Role dependencies
      ansible.builtin.apt:
        name: ['kmod']
        state: present

  roles:
    - ansibleguy.infra_nftables
