---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Checking that config is valid
      ansible.builtin.command: "nft -cf {{ item }}"
      changed_when: false
      loop:
        - '/etc/nftables.d/addons/dns.nft'
        - '/etc/nftables.d/addons/iplist.nft'
        - '/etc/nftables.conf'

    - name: Checking that service survives restart
      ansible.builtin.systemd:
        name: 'nftables.service'
        state: restarted
